### ISSUE TITLE
adhere to NLeSC software checklist

### ISSUE THREAD

**Issue by bakhshir** [candYgene/siga#18]
Check if the repo has everything from the software checklist, in preparation for the release:

Version control

- [x] version control from the beginning of the project
- [x] use git as version control system (vcs)
- [x] choose one branching model
- [x] public vcs repository
- [x] meaningful commit messages **need to work on this**

Releases

- [x] semantic versioning
- [x] tagged releases
- [ ] CHANGELOG.md
- [x] one command install
- [ ] package in package manager
- [ ]  discuss release cycle with coordinator
- [x] release quick-scan by other engineer
- [x] Citeable
- [ ] Dissemination

Licensing

- [x] Apache 2 license
- [x] compatible license of all libraries
- [ ] NOTICE(.txt|.md)

Communication

- [ ] home page
- [ ] discussion list
- [ ] demo docker image in dockerhub (with Dockerfile)
- [ ] an online demo
- [ ] screencast

Code Quality

- [ ] use editorconfig
- [x] code style applied in automated way

Testing

- [ ] unit tests
- [x] continuous integration
- [ ] continuous code coverage
- [ ] end2end test
- [ ] dependencies tracking

Documentation

- [x] README.md
- [x] well defined functionality
- [x] source code documentation
- [x] usage documentation
- [x] documented development setup
- [ ] contribution guidelines
- [ ] code of conduct
- [ ] documented code style
- [ ] how to file a bug report
- [ ] explained meaning of issue labels
- [x] DOI or PID
- [x] CITATION file
- [x] print software version

Development setup

- [ ] dev environment docker images in Dockerhub (with Dockerfile)

Standards

- [x] Exchange formats
- [ ] Protocols
